loglevel = "ERROR"

defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
network = "traefikNetwork"
exposedByDefault = false
